# Generated by Django 3.2.5 on 2021-08-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0023_auto_20210813_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
