# Generated by Django 3.2.5 on 2021-08-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210813_2029'),
        ('customuser', '0024_remove_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='category.Skills'),
        ),
    ]
