# Generated by Django 3.2.5 on 2021-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0024_auto_20210821_2043'),
        ('customuser', '0026_auto_20210821_1618'),
    ]

    operations = [
    ]
