# Generated by Django 3.2.4 on 2021-07-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_request_as_volunteer'),
        ('events', '0007_auto_20210717_1855'),
    ]

    operations = [
    ]
