# Generated by Django 3.2.4 on 2021-07-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge_20210719_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request_as_Volunteer',
        ),
    ]
