# Generated by Django 3.2.4 on 2021-07-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_alter_requestevents_user_details'),
        ('volunteer', '0005_alter_requestevents_description'),
    ]

    operations = [
    ]
